// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using ERP.Domain.Entities;

namespace ERP.Infrastructure.Data;

public partial class ApplicationDbContext : DbContext
{
    public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
        : base(options)
    {
    }

<<<<<<< HEAD
    public virtual DbSet<ProdCategory> Categories { get; set; }
=======
    public virtual DbSet<Brands> Brands { get; set; }

    public virtual DbSet<Categories> Categories { get; set; }
>>>>>>> 3797277c412cfaa00f2cd5a4840a3977aa7e1530

    public virtual DbSet<SalesCustomer> Customers { get; set; }

<<<<<<< HEAD
    public virtual DbSet<ProdBatch> ProductBatches { get; set; }

    public virtual DbSet<ProdSerial> ProductSerials { get; set; }
=======
    public virtual DbSet<Product> Product { get; set; }

    public virtual DbSet<ProductBatches> ProductBatches { get; set; }

    public virtual DbSet<ProductGroup> ProductGroup { get; set; }

    public virtual DbSet<ProductSerials> ProductSerials { get; set; }
>>>>>>> 3797277c412cfaa00f2cd5a4840a3977aa7e1530

    public virtual DbSet<ProdUnitPrice> ProductUnitPrices { get; set; }

<<<<<<< HEAD
    public virtual DbSet<ProdItem> Products { get; set; }
=======
    public virtual DbSet<ProductView> ProductView { get; set; }

    public virtual DbSet<Products> Products { get; set; }
>>>>>>> 3797277c412cfaa00f2cd5a4840a3977aa7e1530

    public virtual DbSet<PurchItem> PurchaseItems { get; set; }

    public virtual DbSet<PurchInvoice> Purchases { get; set; }

    public virtual DbSet<AuthRefreshToken> RefreshTokens { get; set; }

    public virtual DbSet<SalesInvoice> Sales { get; set; }

    public virtual DbSet<SalesInvoiceItem> SalesItems { get; set; }

    public virtual DbSet<InvStockAdjustment> StockAdjustments { get; set; }

    public virtual DbSet<InvStockMovement> StockMovements { get; set; }

    public virtual DbSet<InvStockTransfer> StockTransfers { get; set; }

    public virtual DbSet<PurchSupplier> Suppliers { get; set; }

    public virtual DbSet<ProdUnitConversion> UnitConversions { get; set; }

    public virtual DbSet<ProdUnit> Units { get; set; }

    public virtual DbSet<AuthUser> Users { get; set; }

    public virtual DbSet<InvWarehouseStock> WarehouseStocks { get; set; }

    public virtual DbSet<InvWarehouse> Warehouses { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
<<<<<<< HEAD
        modelBuilder.Entity<ProdCategory>(entity =>
=======
        modelBuilder.Entity<Brands>(entity =>
        {
            entity.HasIndex(e => e.Active, "IX_Brand_Active");

            entity.HasIndex(e => e.Name, "IX_Brand_Name");

            entity.Property(e => e.Id)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.Description)
                .HasMaxLength(255)
                .HasColumnName("description");
            entity.Property(e => e.LastAction).HasMaxLength(50);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
        });

        modelBuilder.Entity<Categories>(entity =>
>>>>>>> 3797277c412cfaa00f2cd5a4840a3977aa7e1530
        {
            entity.HasIndex(e => e.ParentCategoryId, "IX_Categories_ParentCategoryId");

            entity.Property(e => e.Id)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.LastAction).HasMaxLength(50);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ParentCategoryId)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);

            entity.HasOne(d => d.ParentCategory).WithMany(p => p.InverseParentCategory)
                .HasForeignKey(d => d.ParentCategoryId)
                .HasConstraintName("FK_Categories_ParentCategories");
        });

        modelBuilder.Entity<SalesCustomer>(entity =>
        {
            entity.Property(e => e.Id)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.Address)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.City)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ContactPerson).HasMaxLength(50);
            entity.Property(e => e.Country)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreditLimit).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Email)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.LastAction).HasMaxLength(50);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Phone)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.TaxNumber)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
        });

<<<<<<< HEAD
        modelBuilder.Entity<ProdBatch>(entity =>
=======
        modelBuilder.Entity<Product>(entity =>
        {
            entity.HasIndex(e => e.Active, "IX_Product_Active");

            entity.HasIndex(e => e.BaseUnitId, "IX_Product_BaseUnitId");

            entity.HasIndex(e => e.BrandId, "IX_Product_BrandId");

            entity.HasIndex(e => e.CategoryId, "IX_Product_CategoryId");

            entity.HasIndex(e => new { e.CategoryId, e.Active }, "IX_Product_Category_Active");

            entity.HasIndex(e => e.Code, "IX_Product_Code").IsUnique();

            entity.HasIndex(e => e.CreatedAt, "IX_Product_CreatedAt");

            entity.HasIndex(e => e.GroupId, "IX_Product_GroupId");

            entity.HasIndex(e => new { e.GroupId, e.Active }, "IX_Product_Group_Active");

            entity.HasIndex(e => e.Name, "IX_Product_Name");

            entity.HasIndex(e => e.TrackInventory, "IX_Product_TrackInventory");

            entity.HasIndex(e => e.UpdatedAt, "IX_Product_UpdatedAt");

            entity.Property(e => e.Id)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.AllowNegativeStock).HasColumnName("Allow_Negative_Stock");
            entity.Property(e => e.BaseUnitId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("Base_Unit_Id");
            entity.Property(e => e.BrandId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("Brand_Id");
            entity.Property(e => e.CategoryId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("Category_Id");
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.GroupId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("Group_Id");
            entity.Property(e => e.HasBatchNumber).HasColumnName("Has_Batch_Number");
            entity.Property(e => e.HasSerialNumber).HasColumnName("Has_Serial_Number");
            entity.Property(e => e.HasVariant).HasColumnName("Has_Variant");
            entity.Property(e => e.LastAction).HasMaxLength(50);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ReorderLevel).HasColumnName("Reorder_Level");
            entity.Property(e => e.TrackInventory).HasColumnName("Track_Inventory");
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);

            entity.HasOne(d => d.BaseUnit).WithMany(p => p.Product)
                .HasForeignKey(d => d.BaseUnitId)
                .HasConstraintName("FK_Product_Unit");

            entity.HasOne(d => d.Brand).WithMany(p => p.Product)
                .HasForeignKey(d => d.BrandId)
                .HasConstraintName("FK_Product_Brand");

            entity.HasOne(d => d.Category).WithMany(p => p.Product)
                .HasForeignKey(d => d.CategoryId)
                .HasConstraintName("FK_Product_Category");

            entity.HasOne(d => d.Group).WithMany(p => p.Product)
                .HasForeignKey(d => d.GroupId)
                .HasConstraintName("FK_Product_ProductGroup");
        });

        modelBuilder.Entity<ProductBatches>(entity =>
>>>>>>> 3797277c412cfaa00f2cd5a4840a3977aa7e1530
        {
            entity.HasIndex(e => e.ProductId, "IX_ProductBatches_ProductId");

            entity.HasIndex(e => e.WarehouseId, "IX_ProductBatches_WarehouseId");

            entity.Property(e => e.Id)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.BatchNo)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.LastAction).HasMaxLength(50);
            entity.Property(e => e.ProductId)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Quantity).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.WarehouseId)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Product).WithMany(p => p.ProductBatches)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductBatches_Products");

            entity.HasOne(d => d.Warehouse).WithMany(p => p.ProductBatches)
                .HasForeignKey(d => d.WarehouseId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductBatches_Warehouses");
        });

<<<<<<< HEAD
        modelBuilder.Entity<ProdSerial>(entity =>
=======
        modelBuilder.Entity<ProductGroup>(entity =>
        {
            entity.ToTable("Product_Group");

            entity.HasIndex(e => e.Active, "IX_Product_Group_Active");

            entity.HasIndex(e => e.Name, "IX_Product_Group_Name");

            entity.Property(e => e.Id)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.Description)
                .HasMaxLength(255)
                .HasColumnName("description");
            entity.Property(e => e.LastAction).HasMaxLength(50);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
        });

        modelBuilder.Entity<ProductSerials>(entity =>
>>>>>>> 3797277c412cfaa00f2cd5a4840a3977aa7e1530
        {
            entity.HasKey(e => e.Id).HasName("PK_ProductSerials_1");

            entity.Property(e => e.Id)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.LastAction).HasMaxLength(50);
            entity.Property(e => e.ProductId)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Quantity).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.SerialNo)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.WarehouseId)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Product).WithMany(p => p.ProductSerials)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductSerials_Products");

            entity.HasOne(d => d.Warehouse).WithMany(p => p.ProductSerials)
                .HasForeignKey(d => d.WarehouseId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductSerials_Warehouses");
        });

        modelBuilder.Entity<ProdUnitPrice>(entity =>
        {
            entity.HasIndex(e => e.ProductId, "IX_ProductUnitPrices_ProductId");

            entity.HasIndex(e => e.UnitId, "IX_ProductUnitPrices_UnitId");

            entity.Property(e => e.Id)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.LastAction).HasMaxLength(50);
            entity.Property(e => e.ProductId)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.SalePrice).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UnitId)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);

            entity.HasOne(d => d.Product).WithMany(p => p.ProductUnitPrices)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductUnitPrices_Products");

            entity.HasOne(d => d.Unit).WithMany(p => p.ProductUnitPrices)
                .HasForeignKey(d => d.UnitId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductUnitPrices_Units");
        });

<<<<<<< HEAD
        modelBuilder.Entity<ProdItem>(entity =>
=======
        modelBuilder.Entity<ProductView>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("ProductView");

            entity.Property(e => e.AvailableStock).HasColumnType("decimal(38, 2)");
            entity.Property(e => e.Barcode).HasMaxLength(100);
            entity.Property(e => e.BaseUnitName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CategoryName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.Description).HasMaxLength(1000);
            entity.Property(e => e.LastAction).HasMaxLength(50);
            entity.Property(e => e.MaximumStock).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.MinimumStock).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.ProductId)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ReorderLevel).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
        });

        modelBuilder.Entity<Products>(entity =>
>>>>>>> 3797277c412cfaa00f2cd5a4840a3977aa7e1530
        {
            entity.HasIndex(e => e.BaseUnitId, "IX_Products_BaseUnitId");

            entity.HasIndex(e => e.CategoryId, "IX_Products_CategoryId");

            entity.HasIndex(e => e.Code, "IX_Products_Code").IsUnique();

            entity.HasIndex(e => e.Name, "IX_Products_Name");

            entity.Property(e => e.Id)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.Barcode).HasMaxLength(100);
            entity.Property(e => e.BaseUnitId)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CategoryId)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.Description).HasMaxLength(1000);
            entity.Property(e => e.LastAction).HasMaxLength(50);
            entity.Property(e => e.MaximumStock).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.MinimumStock).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.ReorderLevel).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);

            entity.HasOne(d => d.BaseUnit).WithMany(p => p.Products)
                .HasForeignKey(d => d.BaseUnitId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Products_Units");

            entity.HasOne(d => d.Category).WithMany(p => p.Products)
                .HasForeignKey(d => d.CategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Products_Categories");
        });

        modelBuilder.Entity<PurchItem>(entity =>
        {
            entity.HasIndex(e => e.BatchId, "IX_PurchaseItems_BatchId");

            entity.HasIndex(e => e.ProductId, "IX_PurchaseItems_ProductId");

            entity.HasIndex(e => e.PurchaseId, "IX_PurchaseItems_PurchaseId");

            entity.HasIndex(e => e.UnitId, "IX_PurchaseItems_UnitId");

            entity.Property(e => e.Id)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.BatchId)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.DiscountAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.DiscountPercent).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.LastAction).HasMaxLength(50);
            entity.Property(e => e.ProductId)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.PurchaseId)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Quantity).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.SerialId)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.TaxAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TaxPercent).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TotalAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UnitCost).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UnitId)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);

            entity.HasOne(d => d.Batch).WithMany(p => p.PurchaseItems)
                .HasForeignKey(d => d.BatchId)
                .HasConstraintName("FK_PurchaseItems_ProductBatches");

            entity.HasOne(d => d.Product).WithMany(p => p.PurchaseItems)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PurchaseItems_Products");

            entity.HasOne(d => d.Purchase).WithMany(p => p.PurchaseItems)
                .HasForeignKey(d => d.PurchaseId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PurchaseItems_Purchases");

            entity.HasOne(d => d.Serial).WithMany(p => p.PurchaseItems)
                .HasForeignKey(d => d.SerialId)
                .HasConstraintName("FK_PurchaseItems_ProductSerials");

            entity.HasOne(d => d.Unit).WithMany(p => p.PurchaseItems)
                .HasForeignKey(d => d.UnitId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PurchaseItems_Units");
        });

        modelBuilder.Entity<PurchInvoice>(entity =>
        {
            entity.HasIndex(e => e.SupplierId, "IX_Purchases_SupplierId");

            entity.HasIndex(e => e.WarehouseId, "IX_Purchases_WarehouseId");

            entity.Property(e => e.Id)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.LastAction).HasMaxLength(50);
            entity.Property(e => e.PaidAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.PurchaseOrderNumber).IsRequired();
            entity.Property(e => e.SubTotal).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.SupplierId)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.TotalAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TotalDiscount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TotalTax).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.WarehouseId)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Supplier).WithMany(p => p.Purchases)
                .HasForeignKey(d => d.SupplierId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Purchases_Suppliers");

            entity.HasOne(d => d.Warehouse).WithMany(p => p.Purchases)
                .HasForeignKey(d => d.WarehouseId)
                .HasConstraintName("FK_Purchases_Warehouses");
        });

        modelBuilder.Entity<AuthRefreshToken>(entity =>
        {
            entity.HasIndex(e => e.ExpiresAt, "IX_RefreshTokens_ExpiresAt");

            entity.HasIndex(e => e.Token, "IX_RefreshTokens_Token");

            entity.HasIndex(e => e.UserId, "IX_RefreshTokens_UserId");

            entity.Property(e => e.Id)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Token)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.UserId)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<SalesInvoice>(entity =>
        {
            entity.HasIndex(e => e.CustomerId, "IX_Sales_CustomerId");

            entity.HasIndex(e => e.WarehouseId, "IX_Sales_WarehouseId");

            entity.Property(e => e.Id)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CustomerId)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.InvoiceNumber)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.LastAction).HasMaxLength(50);
            entity.Property(e => e.PaidAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.SubTotal).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TotalAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TotalDiscount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TotalTax).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.WarehouseId)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Customer).WithMany(p => p.Sales)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Sales_Customers");

            entity.HasOne(d => d.Warehouse).WithMany(p => p.Sales)
                .HasForeignKey(d => d.WarehouseId)
                .HasConstraintName("FK_Sales_Warehouses");
        });

        modelBuilder.Entity<SalesInvoiceItem>(entity =>
        {
            entity.HasIndex(e => e.BatchId, "IX_SalesItems_BatchId");

            entity.HasIndex(e => e.ProductId, "IX_SalesItems_ProductId");

            entity.HasIndex(e => e.SaleId, "IX_SalesItems_SaleId");

            entity.HasIndex(e => e.SerialId, "IX_SalesItems_SerialId");

            entity.HasIndex(e => e.UnitId, "IX_SalesItems_UnitId");

            entity.Property(e => e.Id)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.BatchId)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.DiscountAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.DiscountPercent).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.LastAction).HasMaxLength(50);
            entity.Property(e => e.ProductId)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Quantity).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.SaleId)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.SerialId)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.TaxAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TaxPercent).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TotalAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UnitId)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UnitPrice).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);

            entity.HasOne(d => d.Batch).WithMany(p => p.SalesItems)
                .HasForeignKey(d => d.BatchId)
                .HasConstraintName("FK_SalesItems_ProductBatches");

            entity.HasOne(d => d.Product).WithMany(p => p.SalesItems)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SalesItems_Products");

            entity.HasOne(d => d.Sale).WithMany(p => p.SalesItems)
                .HasForeignKey(d => d.SaleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SalesItems_Sales");

            entity.HasOne(d => d.Serial).WithMany(p => p.SalesItems)
                .HasForeignKey(d => d.SerialId)
                .HasConstraintName("FK_SalesItems_ProductSerials");

            entity.HasOne(d => d.Unit).WithMany(p => p.SalesItems)
                .HasForeignKey(d => d.UnitId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SalesItems_Units");
        });

        modelBuilder.Entity<InvStockAdjustment>(entity =>
        {
            entity.HasIndex(e => e.ProductId, "IX_StockAdjustments_ProductId");

            entity.HasIndex(e => e.WarehouseId, "IX_StockAdjustments_WarehouseId");

            entity.Property(e => e.Id)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.AdjustmentNo)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.AdjustmentQuantity).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.LastAction).HasMaxLength(50);
            entity.Property(e => e.ProductId)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Reason).IsRequired();
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.WarehouseId)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Product).WithMany(p => p.StockAdjustments)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_StockAdjustments_Products");

            entity.HasOne(d => d.Warehouse).WithMany(p => p.StockAdjustments)
                .HasForeignKey(d => d.WarehouseId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_StockAdjustments_Warehouses");
        });

        modelBuilder.Entity<InvStockMovement>(entity =>
        {
            entity.HasIndex(e => e.BatchId, "IX_StockMovements_BatchId");

            entity.HasIndex(e => e.ProductId, "IX_StockMovements_ProductId");

            entity.HasIndex(e => e.WarehouseId, "IX_StockMovements_WarehouseId");

            entity.Property(e => e.Id)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.BaseQuantity).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.BatchId)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.LastAction).HasMaxLength(50);
            entity.Property(e => e.MovementType)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ProductId)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ReferenceId)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.SerialId)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.WarehouseId)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Batch).WithMany(p => p.StockMovements)
                .HasForeignKey(d => d.BatchId)
                .HasConstraintName("FK_StockMovements_ProductBatches");

            entity.HasOne(d => d.Product).WithMany(p => p.StockMovements)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_StockMovements_Products");

            entity.HasOne(d => d.Serial).WithMany(p => p.StockMovements)
                .HasForeignKey(d => d.SerialId)
                .HasConstraintName("FK_StockMovements_ProductSerials");

            entity.HasOne(d => d.Warehouse).WithMany(p => p.StockMovements)
                .HasForeignKey(d => d.WarehouseId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_StockMovements_Warehouses");
        });

        modelBuilder.Entity<InvStockTransfer>(entity =>
        {
            entity.HasIndex(e => e.FromWarehouseId, "IX_StockTransfers_FromWarehouseId");

            entity.HasIndex(e => e.ProductId, "IX_StockTransfers_ProductId");

            entity.HasIndex(e => e.ToWarehouseId, "IX_StockTransfers_ToWarehouseId");

            entity.HasIndex(e => e.TransferNo, "IX_StockTransfers_TransferNo").IsUnique();

            entity.Property(e => e.Id)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.FromWarehouseId)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.LastAction).HasMaxLength(50);
            entity.Property(e => e.ProductId)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Quantity).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.ToWarehouseId)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.TransferNo)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);

            entity.HasOne(d => d.FromWarehouse).WithMany(p => p.StockTransfersFromWarehouse)
                .HasForeignKey(d => d.FromWarehouseId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_StockTransfers_Warehouses");

            entity.HasOne(d => d.Product).WithMany(p => p.StockTransfers)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_StockTransfers_Products");

            entity.HasOne(d => d.ToWarehouse).WithMany(p => p.StockTransfersToWarehouse)
                .HasForeignKey(d => d.ToWarehouseId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_StockTransfers_Warehouses1");
        });

        modelBuilder.Entity<PurchSupplier>(entity =>
        {
            entity.Property(e => e.Id)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.Address)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.City)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ContactPerson)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Country)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.Email)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.LastAction).HasMaxLength(50);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Phone)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.TaxNumber)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
        });

        modelBuilder.Entity<ProdUnitConversion>(entity =>
        {
            entity.HasIndex(e => e.FromUnitId, "IX_UnitConversions_FromUnitId");

            entity.HasIndex(e => new { e.ProductId, e.FromUnitId, e.ToUnitId }, "IX_UnitConversions_ProductId_FromUnitId_ToUnitId").IsUnique();

            entity.HasIndex(e => e.ToUnitId, "IX_UnitConversions_ToUnitId");

            entity.Property(e => e.Id)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.Factor).HasColumnType("decimal(18, 6)");
            entity.Property(e => e.FromUnitId)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.LastAction).HasMaxLength(50);
            entity.Property(e => e.ProductId)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ToUnitId)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);

            entity.HasOne(d => d.FromUnit).WithMany(p => p.UnitConversionsFromUnit)
                .HasForeignKey(d => d.FromUnitId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UnitConversions_Units");

            entity.HasOne(d => d.Product).WithMany(p => p.UnitConversions)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UnitConversions_Products");

            entity.HasOne(d => d.ToUnit).WithMany(p => p.UnitConversionsToUnit)
                .HasForeignKey(d => d.ToUnitId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UnitConversions_Units1");
        });

        modelBuilder.Entity<ProdUnit>(entity =>
        {
            entity.HasIndex(e => e.Active, "IX_Unit_Active");

            entity.HasIndex(e => e.Name, "IX_Unit_Name");

            entity.HasIndex(e => e.Symbol, "IX_Unit_Symbol").IsUnique();

            entity.Property(e => e.Id)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.LastAction).HasMaxLength(50);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.Symbol)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
        });

        modelBuilder.Entity<AuthUser>(entity =>
        {
            entity.HasIndex(e => e.Email, "IX_Users_Email").IsUnique();

            entity.HasIndex(e => e.Username, "IX_Users_Username").IsUnique();

            entity.Property(e => e.Id)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.FirstName).HasMaxLength(100);
            entity.Property(e => e.LastAction).HasMaxLength(50);
            entity.Property(e => e.LastName).HasMaxLength(100);
            entity.Property(e => e.PasswordHash).IsRequired();
            entity.Property(e => e.Role)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("User");
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<InvWarehouseStock>(entity =>
        {
            entity.HasIndex(e => e.ProductId, "IX_WarehouseStocks_ProductId");

            entity.HasIndex(e => e.WarehouseId, "IX_WarehouseStocks_WarehouseId");

            entity.Property(e => e.Id)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.AvailableQuantity).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.LastAction).HasMaxLength(50);
            entity.Property(e => e.ProductId)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ReservedQuantity).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
            entity.Property(e => e.WarehouseId)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Product).WithMany(p => p.WarehouseStocks)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_WarehouseStocks_Products");

            entity.HasOne(d => d.Warehouse).WithMany(p => p.WarehouseStocks)
                .HasForeignKey(d => d.WarehouseId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_WarehouseStocks_Warehouses");
        });

        modelBuilder.Entity<InvWarehouse>(entity =>
        {
            entity.HasIndex(e => e.Active, "IX_Warehouse_Active");

            entity.HasIndex(e => e.BranchType, "IX_Warehouse_BranchType");

            entity.HasIndex(e => e.IsMainWarehouse, "IX_Warehouse_IsMainWarehouse");

            entity.HasIndex(e => new { e.Name, e.City }, "IX_Warehouse_Name_City");

            entity.HasIndex(e => e.ParentWarehouseId, "IX_Warehouse_ParentWarehouseId");

            entity.Property(e => e.Id)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.Address).HasMaxLength(255);
            entity.Property(e => e.BranchType)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.City).HasMaxLength(50);
            entity.Property(e => e.ContactPerson).HasMaxLength(100);
            entity.Property(e => e.Country).HasMaxLength(50);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.IsUsedWarehouse).HasDefaultValue(true);
            entity.Property(e => e.LastAction).HasMaxLength(50);
            entity.Property(e => e.Location).HasMaxLength(100);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ParentWarehouseId).HasMaxLength(50);
            entity.Property(e => e.Phone).HasMaxLength(20);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}