// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERP.Domain.Entities;

public partial class Brands
{
    public string Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string Remark { get; set; }

    public bool Active { get; set; }

    public string LastAction { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }
}