// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERP.Domain.Entities;

public partial class InvStockMovement
{
    public string Id { get; set; }

    public string ProductId { get; set; }

    public string WarehouseId { get; set; }

    public string MovementType { get; set; }

    public int ReferenceType { get; set; }

    public string ReferenceId { get; set; }

    public decimal BaseQuantity { get; set; }

    public string BatchId { get; set; }

    public string SerialId { get; set; }

    public DateTime MovementDate { get; set; }

    public string Notes { get; set; }

    public bool Active { get; set; }

    public DateTime CreatedAt { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string UpdatedBy { get; set; }

    public string LastAction { get; set; }

    public virtual ProdBatch Batch { get; set; }

    public virtual ProdItem Product { get; set; }

    public virtual ProdSerial Serial { get; set; }

    public virtual InvWarehouse Warehouse { get; set; }
}
