// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERP.Domain.Entities;

public partial class Warehouses
{
    public string Id { get; set; }

    public string Name { get; set; }

    public string City { get; set; }

    public string BranchType { get; set; }

    public bool IsMainWarehouse { get; set; }

    public string ParentWarehouseId { get; set; }

    public bool IsUsedWarehouse { get; set; }

    public string Location { get; set; }

    public string Address { get; set; }

    public string Country { get; set; }

    public string ContactPerson { get; set; }

    public string Phone { get; set; }

    public bool Active { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public string LastAction { get; set; }

    public virtual ICollection<ProductBatches> ProductBatches { get; set; } = new List<ProductBatches>();

    public virtual ICollection<ProductSerials> ProductSerials { get; set; } = new List<ProductSerials>();

    public virtual ICollection<Purchases> Purchases { get; set; } = new List<Purchases>();

    public virtual ICollection<Sales> Sales { get; set; } = new List<Sales>();

    public virtual ICollection<StockAdjustments> StockAdjustments { get; set; } = new List<StockAdjustments>();

    public virtual ICollection<StockMovements> StockMovements { get; set; } = new List<StockMovements>();

    public virtual ICollection<StockTransfers> StockTransfersFromWarehouse { get; set; } = new List<StockTransfers>();

    public virtual ICollection<StockTransfers> StockTransfersToWarehouse { get; set; } = new List<StockTransfers>();

    public virtual ICollection<WarehouseStocks> WarehouseStocks { get; set; } = new List<WarehouseStocks>();
}