// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERP.Domain.Entities;

public partial class InvWarehouseStock
{
    public string Id { get; set; }

    public string WarehouseId { get; set; }

    public string ProductId { get; set; }

    public decimal AvailableQuantity { get; set; }

    public decimal ReservedQuantity { get; set; }

    public bool Active { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public string LastAction { get; set; }

    public virtual ProdItem Product { get; set; }

    public virtual InvWarehouse Warehouse { get; set; }
}
