// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERP.Domain.Entities;

public partial class InvWarehouse
{
    public string Id { get; set; }

    public string Name { get; set; }

    public string City { get; set; }

    public string BranchType { get; set; }

    public bool IsMainWarehouse { get; set; }

    public string ParentWarehouseId { get; set; }

    public bool IsUsedWarehouse { get; set; }

    public string Location { get; set; }

    public string Address { get; set; }

    public string Country { get; set; }

    public string ContactPerson { get; set; }

    public string Phone { get; set; }

    public bool Active { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public string LastAction { get; set; }

    public virtual ICollection<InvStockAdjustment> InvStockAdjustment { get; set; } = new List<InvStockAdjustment>();

    public virtual ICollection<InvStockMovement> InvStockMovement { get; set; } = new List<InvStockMovement>();

    public virtual ICollection<InvStockTransfer> InvStockTransferFromWarehouse { get; set; } = new List<InvStockTransfer>();

    public virtual ICollection<InvStockTransfer> InvStockTransferToWarehouse { get; set; } = new List<InvStockTransfer>();

    public virtual ICollection<InvWarehouseStock> InvWarehouseStock { get; set; } = new List<InvWarehouseStock>();

    public virtual ICollection<ProdBatch> ProdBatch { get; set; } = new List<ProdBatch>();

    public virtual ICollection<ProdSerial> ProdSerial { get; set; } = new List<ProdSerial>();

    public virtual ICollection<PurchInvoice> PurchInvoice { get; set; } = new List<PurchInvoice>();

    public virtual ICollection<SalesInvoice> SalesInvoice { get; set; } = new List<SalesInvoice>();
}