// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERP.Domain.Entities;

public partial class ProdBatch
{
    public string Id { get; set; }

    public string ProductId { get; set; }

    public string WarehouseId { get; set; }

    public string BatchNo { get; set; }

    public decimal Quantity { get; set; }

    public DateTime? ManufactureDate { get; set; }

    public DateTime? ExpiryDate { get; set; }

    public bool Active { get; set; }

    public DateTime CreatedAt { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string UpdatedBy { get; set; }

    public string LastAction { get; set; }

    public virtual ProdItem Product { get; set; }

    public virtual ICollection<PurchItem> PurchaseItems { get; set; } = new List<PurchItem>();

    public virtual ICollection<SalesInvoiceItem> SalesItems { get; set; } = new List<SalesInvoiceItem>();

    public virtual ICollection<InvStockMovement> StockMovements { get; set; } = new List<InvStockMovement>();

    public virtual InvWarehouse Warehouse { get; set; }
}
