// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERP.Domain.Entities;

public partial class ProductUnitPrices
{
    public string Id { get; set; }

    public string ProductId { get; set; }

    public string UnitId { get; set; }

    public decimal SalePrice { get; set; }

    public bool Active { get; set; }

    public DateTime CreatedAt { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string UpdatedBy { get; set; }

    public string LastAction { get; set; }

    public virtual Products Product { get; set; }

    public virtual Units Unit { get; set; }
}