// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERP.Domain.Entities;

public partial class ProdUnit
{
    public string Id { get; set; }

    public string Name { get; set; }

    public string Symbol { get; set; }

    public bool Active { get; set; }

    public DateTime CreatedAt { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string UpdatedBy { get; set; }

    public string LastAction { get; set; }

    public virtual ICollection<ProdUnitPrice> ProductUnitPrices { get; set; } = new List<ProdUnitPrice>();

    public virtual ICollection<ProdItem> Products { get; set; } = new List<ProdItem>();

    public virtual ICollection<PurchItem> PurchaseItems { get; set; } = new List<PurchItem>();

    public virtual ICollection<SalesInvoiceItem> SalesItems { get; set; } = new List<SalesInvoiceItem>();

    public virtual ICollection<ProdUnitConversion> UnitConversionsFromUnit { get; set; } = new List<ProdUnitConversion>();

    public virtual ICollection<ProdUnitConversion> UnitConversionsToUnit { get; set; } = new List<ProdUnitConversion>();
}