// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERP.Domain.Entities;

public partial class ProdUnit
{
    public string Id { get; set; }

    public string Name { get; set; }

    public string Symbol { get; set; }

    public bool Active { get; set; }

    public DateTime CreatedAt { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string UpdatedBy { get; set; }

    public string LastAction { get; set; }

    public virtual ICollection<ProdItem> ProdItem { get; set; } = new List<ProdItem>();

    public virtual ICollection<ProdUnitConversion> ProdUnitConversionFromUnit { get; set; } = new List<ProdUnitConversion>();

    public virtual ICollection<ProdUnitConversion> ProdUnitConversionToUnit { get; set; } = new List<ProdUnitConversion>();

    public virtual ICollection<ProdUnitPrice> ProdUnitPrice { get; set; } = new List<ProdUnitPrice>();

    public virtual ICollection<PurchItem> PurchItem { get; set; } = new List<PurchItem>();

    public virtual ICollection<SalesInvoiceItem> SalesInvoiceItem { get; set; } = new List<SalesInvoiceItem>();
}