// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERP.Domain.Entities;

public partial class ProdItem
{
    public string Id { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public string GroupId { get; set; }

    public string CategoryId { get; set; }

    public string BrandId { get; set; }

    public string Description { get; set; }

    public string BaseUnitId { get; set; }

    public decimal? MinimumStock { get; set; }

    public decimal? MaximumStock { get; set; }

    public decimal? ReorderLevel { get; set; }

    public string Barcode { get; set; }

    public int TrackType { get; set; }

    public bool HasVariant { get; set; }

    public bool? AllowNegativeStock { get; set; }

    public bool Active { get; set; }

    public DateTime CreatedAt { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string UpdatedBy { get; set; }

    public string LastAction { get; set; }

    public virtual ProdUnit BaseUnit { get; set; }

    public virtual ProdBrand Brand { get; set; }

    public virtual ProdCategory Category { get; set; }

    public virtual ProdGroup Group { get; set; }

    public virtual ICollection<InvStockAdjustment> InvStockAdjustment { get; set; } = new List<InvStockAdjustment>();

    public virtual ICollection<InvStockMovement> InvStockMovement { get; set; } = new List<InvStockMovement>();

    public virtual ICollection<InvStockTransfer> InvStockTransfer { get; set; } = new List<InvStockTransfer>();

    public virtual ICollection<InvWarehouseStock> InvWarehouseStock { get; set; } = new List<InvWarehouseStock>();

    public virtual ICollection<ProdBatch> ProdBatch { get; set; } = new List<ProdBatch>();

    public virtual ICollection<ProdSerial> ProdSerial { get; set; } = new List<ProdSerial>();

    public virtual ICollection<ProdUnitConversion> ProdUnitConversion { get; set; } = new List<ProdUnitConversion>();

    public virtual ICollection<ProdUnitPrice> ProdUnitPrice { get; set; } = new List<ProdUnitPrice>();

    public virtual ICollection<PurchItem> PurchItem { get; set; } = new List<PurchItem>();

    public virtual ICollection<SalesInvoiceItem> SalesInvoiceItem { get; set; } = new List<SalesInvoiceItem>();
}