// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERP.Domain.Entities;

public partial class Products
{
    public string Id { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string CategoryId { get; set; }

    public string BaseUnitId { get; set; }

    public decimal? MinimumStock { get; set; }

    public decimal? MaximumStock { get; set; }

    public decimal? ReorderLevel { get; set; }

    public string Barcode { get; set; }

    public bool IsBatchTracked { get; set; }

    public bool IsSerialTracked { get; set; }

    public bool Active { get; set; }

    public DateTime CreatedAt { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string UpdatedBy { get; set; }

    public string LastAction { get; set; }

    public virtual Units BaseUnit { get; set; }

    public virtual Categories Category { get; set; }

    public virtual ICollection<ProductBatches> ProductBatches { get; set; } = new List<ProductBatches>();

    public virtual ICollection<ProductSerials> ProductSerials { get; set; } = new List<ProductSerials>();

    public virtual ICollection<ProductUnitPrices> ProductUnitPrices { get; set; } = new List<ProductUnitPrices>();

    public virtual ICollection<PurchaseItems> PurchaseItems { get; set; } = new List<PurchaseItems>();

    public virtual ICollection<SalesItems> SalesItems { get; set; } = new List<SalesItems>();

    public virtual ICollection<StockAdjustments> StockAdjustments { get; set; } = new List<StockAdjustments>();

    public virtual ICollection<StockMovements> StockMovements { get; set; } = new List<StockMovements>();

    public virtual ICollection<StockTransfers> StockTransfers { get; set; } = new List<StockTransfers>();

    public virtual ICollection<UnitConversions> UnitConversions { get; set; } = new List<UnitConversions>();

    public virtual ICollection<WarehouseStocks> WarehouseStocks { get; set; } = new List<WarehouseStocks>();
}