// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERP.Domain.Entities;

public partial class ProdItem
{
    public string Id { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string CategoryId { get; set; }

    public string BaseUnitId { get; set; }

    public decimal? MinimumStock { get; set; }

    public decimal? MaximumStock { get; set; }

    public decimal? ReorderLevel { get; set; }

    public string Barcode { get; set; }

    public bool IsBatchTracked { get; set; }

    public bool IsSerialTracked { get; set; }

    public bool Active { get; set; }

    public DateTime CreatedAt { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string UpdatedBy { get; set; }

    public string LastAction { get; set; }

    public virtual ProdUnit BaseUnit { get; set; }

    public virtual ProdCategory Category { get; set; }

    public virtual ICollection<ProdBatch> ProductBatches { get; set; } = new List<ProdBatch>();

    public virtual ICollection<ProdSerial> ProductSerials { get; set; } = new List<ProdSerial>();

    public virtual ICollection<ProdUnitPrice> ProductUnitPrices { get; set; } = new List<ProdUnitPrice>();

    public virtual ICollection<PurchItem> PurchaseItems { get; set; } = new List<PurchItem>();

    public virtual ICollection<SalesInvoiceItem> SalesItems { get; set; } = new List<SalesInvoiceItem>();

    public virtual ICollection<InvStockAdjustment> StockAdjustments { get; set; } = new List<InvStockAdjustment>();

    public virtual ICollection<InvStockMovement> StockMovements { get; set; } = new List<InvStockMovement>();

    public virtual ICollection<InvStockTransfer> StockTransfers { get; set; } = new List<InvStockTransfer>();

    public virtual ICollection<ProdUnitConversion> UnitConversions { get; set; } = new List<ProdUnitConversion>();

    public virtual ICollection<InvWarehouseStock> WarehouseStocks { get; set; } = new List<InvWarehouseStock>();
}
