// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERP.Domain.Entities;

public partial class ProdUnitConversion
{
    public string Id { get; set; }

    public string ProductId { get; set; }

    public string FromUnitId { get; set; }

    public string ToUnitId { get; set; }

    public decimal Factor { get; set; }

    public bool Active { get; set; }

    public DateTime CreatedAt { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string UpdatedBy { get; set; }

    public string LastAction { get; set; }

    public virtual ProdUnit FromUnit { get; set; }

    public virtual ProdItem Product { get; set; }

    public virtual ProdUnit ToUnit { get; set; }
}
