// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERP.Domain.Entities;

public partial class Product
{
    public string Id { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public string GroupId { get; set; }

    public string CategoryId { get; set; }

    public string BrandId { get; set; }

    public string BaseUnitId { get; set; }

    public bool TrackInventory { get; set; }

    public bool HasVariant { get; set; }

    public bool HasSerialNumber { get; set; }

    public bool HasBatchNumber { get; set; }

    public int? ReorderLevel { get; set; }

    public bool AllowNegativeStock { get; set; }

    public bool Active { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public string LastAction { get; set; }

    public virtual Units BaseUnit { get; set; }

    public virtual Brands Brand { get; set; }

    public virtual Categories Category { get; set; }

    public virtual ProductGroup Group { get; set; }
}