// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERP.Domain.Entities;

public partial class ProdCategory
{
    public string Id { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public string ParentCategoryId { get; set; }

    public string Description { get; set; }

    public bool IsUsed { get; set; }

    public bool Active { get; set; }

    public DateTime CreatedAt { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string UpdatedBy { get; set; }

    public string LastAction { get; set; }

    public virtual ICollection<ProdCategory> InverseParentCategory { get; set; } = new List<ProdCategory>();

    public virtual ProdCategory ParentCategory { get; set; }

    public virtual ICollection<ProdItem> ProdItem { get; set; } = new List<ProdItem>();
}