// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERP.Domain.Entities;

public partial class PurchaseItems
{
    public string Id { get; set; }

    public string PurchaseId { get; set; }

    public string ProductId { get; set; }

    public string UnitId { get; set; }

    public decimal Quantity { get; set; }

    public decimal UnitCost { get; set; }

    public decimal? DiscountPercent { get; set; }

    public decimal? DiscountAmount { get; set; }

    public decimal? TaxPercent { get; set; }

    public decimal? TaxAmount { get; set; }

    public decimal TotalAmount { get; set; }

    public string Notes { get; set; }

    public string BatchId { get; set; }

    public string SerialId { get; set; }

    public bool Active { get; set; }

    public DateTime CreatedAt { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string UpdatedBy { get; set; }

    public string LastAction { get; set; }

    public virtual ProductBatches Batch { get; set; }

    public virtual Products Product { get; set; }

    public virtual Purchases Purchase { get; set; }

    public virtual ProductSerials Serial { get; set; }

    public virtual Units Unit { get; set; }
}