// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERP.Domain.Entities;

public partial class Sales
{
    public string Id { get; set; }

    public string InvoiceNumber { get; set; }

    public DateTime SaleDate { get; set; }

    public string CustomerId { get; set; }

    public string WarehouseId { get; set; }

    public decimal SubTotal { get; set; }

    public decimal? TotalDiscount { get; set; }

    public decimal? TotalTax { get; set; }

    public decimal TotalAmount { get; set; }

    public decimal? PaidAmount { get; set; }

    public int PaymentStatus { get; set; }

    public int Status { get; set; }

    public DateTime? DueDate { get; set; }

    public string Notes { get; set; }

    public bool Active { get; set; }

    public DateTime CreatedAt { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string UpdatedBy { get; set; }

    public string LastAction { get; set; }

    public virtual Customers Customer { get; set; }

    public virtual ICollection<SalesItems> SalesItems { get; set; } = new List<SalesItems>();

    public virtual Warehouses Warehouse { get; set; }
}