// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERP.Domain.Entities;

public partial class StockTransfers
{
    public string Id { get; set; }

    public string TransferNo { get; set; }

    public string FromWarehouseId { get; set; }

    public string ToWarehouseId { get; set; }

    public string ProductId { get; set; }

    public decimal Quantity { get; set; }

    public DateTime TransferDate { get; set; }

    public int Status { get; set; }

    public string Notes { get; set; }

    public bool Active { get; set; }

    public DateTime CreatedAt { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string UpdatedBy { get; set; }

    public string LastAction { get; set; }

    public virtual Warehouses FromWarehouse { get; set; }

    public virtual Products Product { get; set; }

    public virtual Warehouses ToWarehouse { get; set; }
}