// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERP.Domain.Entities;

public partial class Units
{
    public string Id { get; set; }

    public string Name { get; set; }

    public string Symbol { get; set; }

    public bool Active { get; set; }

    public DateTime CreatedAt { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string UpdatedBy { get; set; }

    public string LastAction { get; set; }

    public virtual ICollection<Product> Product { get; set; } = new List<Product>();


    public virtual ICollection<ProductUnitPrices> ProductUnitPrices { get; set; } = new List<ProductUnitPrices>();

    public virtual ICollection<Products> Products { get; set; } = new List<Products>();

    public virtual ICollection<PurchaseItems> PurchaseItems { get; set; } = new List<PurchaseItems>();

    public virtual ICollection<SalesItems> SalesItems { get; set; } = new List<SalesItems>();

    public virtual ICollection<UnitConversions> UnitConversionsFromUnit { get; set; } = new List<UnitConversions>();

    public virtual ICollection<UnitConversions> UnitConversionsToUnit { get; set; } = new List<UnitConversions>();
}