// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERP.Domain.Entities;

public partial class VwProdUnitConversion
{
    public string Id { get; set; }

    public string ProductId { get; set; }

    public string ProductCode { get; set; }

    public string ProductName { get; set; }

    public string FromUnitId { get; set; }

    public string FromUnitName { get; set; }

    public string FromUnitSymbol { get; set; }

    public string ToUnitId { get; set; }

    public string ToUnitName { get; set; }

    public string ToUnitSymbol { get; set; }

    public decimal Factor { get; set; }

    public bool Active { get; set; }

    public DateTime CreatedAt { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string UpdatedBy { get; set; }

    public string LastAction { get; set; }
}